general {
    lock_cmd = pidof hyprlock || hyprlock       # Запускати hyprlock, якщо він ще не запущений
    before_sleep_cmd = loginctl lock-session    # Викликати команду блокування ПЕРЕД сном
    after_sleep_cmd = hyprctl dispatch dpms on  # Гарантовано вмикати дисплей ПІСЛЯ пробудження
}

# Опціонально: блокувати екран через 5 хвилин бездіяльності
listener {
    timeout = 300                                 # 5 хвилин
    on-timeout = loginctl lock-session
}

# Опціонально: вимикати дисплей через 5.5 хвилин бездіяльності (економія батареї)
listener {
    timeout = 330                                 
    on-timeout = hyprctl dispatch dpms off        
    on-resume = hyprctl dispatch dpms on          
}

# Сон через 10 хвилин
listener {
	timeout = 600
	on-timeout = systemctl suspend
}
