background {
	monitor =
	path = ~/.config/wallpapers/lock/nasa.png
	blur_passes = 0.5
	blur_pize = 1
	noise = 0.0117
	contrast = 0.8916
	brightness = 0.8172
	vibrancy = 0.1696
	vibrancy_darkness = 0.0
}

label {
	monitor =
	text = $TIME
	color = rgb(205, 214, 244)
	font_size = 100
	font_family = JetBrainsMono Nerd Font Bold
	position = -150, 250
	halign = right
	valign = center
}
# Batt Widget shape

shape {
	monitor =
	color = rgb(49, 50, 68)
	rounding = 15
	halign = center
	valign = top
	position = 0, -10
	size = 300, 30
}
# KB Widget shape

shape {
	monitor = 
	color = rgb(49, 50, 68)
	rounding = 5
	halign = left
	valign = top
	position = 10, -10 
	size = 30, 30
}
# Battary
label{
	monitor =
	text = cmd[update:20000] ~/.config/hyperscripts/hyprlock/battary.sh
	color = rgb(166, 227,161)
	font_size = 11
	font_family = JetBrainsMono Nerd Font 
	position = 120, -15
	halign = center 
	valign = top
	rounding = 5
	border_color = rgb(0, 0, 0)
}
label {
	monitor =
	text = cmd[update:1000] ~/.config/hyperscripts/hyprlock/kb_layaut.sh 
	color = rbg(148,163,184)
	font_size = 11
	font_family = JetBrainsMono Nerd Font
	position = 15, -15
	halign = left
	valign = top
}
# Player status
label {
	monitor = 
	text = cmd[update:2000] ~/.config/hyperscripts/hyprlock/player.sh
	color = rgb(25, 183, 71)
	font_size = 11 
	font_family = JetBrainsMono Nerd Font
	position = -35, -15
	halign = center
	valign = top
}

# Date

label {
	monitor = 
	text = cmd[] ~/.config/hyperscripts/hyprlock/date.sh
	color = rgb(205,214,244) 
	font_size = 20
	font_family = JetBrainsMono Nerd Font Bold
	position = -350, 325
	halign = right
	valign = center
}

label {
	monitor = 
	text = <i><b>$USER</b></i>
	color = rgb(205, 214, 244)
	font_size = 20 
	font_family = JetBrainsMono Nerd Font
	position = -270, 0 
	halign = right 
	valign = center
}

input-field {
	monitor = 
	size = 300, 30
	outlie_thickness = 1 
	dots_size = 0.33
	dots_spacing = 0.15
	dots_center = true
	dots_rounding = -1

	outer_color = rgb(255, 255, 255)
	inner_color = rgba(255,255,255,0)
	font_color = rgb(205, 214, 244)

	fade_on_empty = false
	fade_timeout = 1000
	placeholder_text = <i>ENTER PASSWORD...</i>
	hide_input = false
	rounding = 15 
	check_color = rgb(249, 226, 175)
	fail_color = rgb(243, 139, 168)
	fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
	fail_transition = 300

	position = -200, -300
	halign = right 
	valign = center

}
