# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }


windowrule {
    name = gimp-pdf-import
    match:class = ^(Gimp|gimp)$
    match:title = ^(Import from PDF|Імпортувати.*|Import.*)$
    float = on
    center = on
    stay_focused = on
}
windowrule {
    name = gimp-pdf-load
    match:class = ^(file-pdf-load)$
    float = true
    center = true
}
windowrule {
    name = gimp-plugins-float
    match:class = ^(file-.*-load|plug-in-.*)$
    float = true
    center = true
}
